// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnxhttnmlauoxgocwyyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBueGh0dG5tbGF1b3hnb2N3eXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzA1NjEsImV4cCI6MjA2NjkwNjU2MX0.YftpUBBf0YAZHILdETiUIjmTwY5V3M7rz9AlTo7UnzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});